name: Python
on: push
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See https://pypi.org/project/OctoPrint/
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install OctoPrint
    - name: Install test dependencies
      run: pip install mock testcontainers-compose
    - name: Run unit tests
      run: python -m unittest discover
    - name: Run integration tests
      run: python -m unittest discover -p "integration_*.py"
    - name: Install module
      run: pip install -e .
